# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FobbidenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=40, verbose_name='\u7528\u6237\u540d')),
                ('pt', models.SmallIntegerField(choices=[(0, '\u81ea\u5efa\u6e20\u9053')], default=0, verbose_name='\u8ba4\u8bc1\u5e73\u53f0(\u6e20\u9053\u7f16\u53f7)')),
                ('date_expire', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('date_log', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
            ],
            options={
                'db_table': 'fobbidenuser',
                'verbose_name': '\u5c01\u7981\u7528\u6237',
                'verbose_name_plural': '\u5c01\u7981\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='OAuthUser_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=40, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='\u5bc6\u7801')),
                ('pt', models.SmallIntegerField(choices=[(0, '\u81ea\u5efa\u6e20\u9053')], default=0, verbose_name='\u8ba4\u8bc1\u5e73\u53f0(\u6e20\u9053\u7f16\u53f7)')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4e00\u6b21\u767b\u5f55\u65f6\u95f4')),
            ],
            options={
                'db_table': 'oauthuser_0',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AlterUniqueTogether(
            name='oauthuser_0',
            unique_together=set([('username', 'pt')]),
        ),
    ]
