# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser_0',
            name='salt',
            field=models.CharField(default='huangxin', max_length=10, verbose_name='\u52a0\u5bc6salt'),
            preserve_default=False,
        ),
    ]
