# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('address', models.CharField(default='{}', help_text="\u683c\u5f0f:{'ip\u5730\u5740':[\u7aef\u53e3\u53f7\u5217\u8868]}", max_length=500, verbose_name='\u5206\u53d1\u670d\u52a1\u5668\u5217\u8868')),
                ('baddress', models.CharField(default='[]', help_text='\u683c\u5f0f:[ip\u5730\u5740, \u7aef\u53e3],\u8fd9\u4e2a\u53ea\u6709\u4e00\u4e2a', max_length=100, verbose_name='\u670d\u52a1\u5668\u56de\u8c03\u5730\u5740')),
                ('s_st', models.SmallIntegerField(choices=[(1, '---\u65b0\u670d---'), (2, '---\u6d41\u7545---'), (3, '---\u706b\u7206---'), (4, '---\u7ef4\u62a4\u4e2d---'), (5, '---\u6b63\u5728\u6e20\u9053\u5ba1\u6838---')], default=1, verbose_name='\u670d\u52a1\u5668\u72b6\u6001')),
                ('d_st', models.SmallIntegerField(choices=[(1, '--\u663e\u793a--'), (2, '--\u4e0d\u663e\u793a--'), (3, '--\u63a8\u8350--')], default=1, verbose_name='\u670d\u52a1\u5668\u663e\u793a')),
            ],
            options={
                'db_table': 'gameserver',
                'verbose_name': '\u533a\u670d/\u670d\u52a1\u5668\u7ec4',
                'verbose_name_plural': '\u533a\u670d/\u670d\u52a1\u5668\u7ec4',
            },
        ),
    ]
